name: Check and fix PHP Coding Standards

on:
  pull_request:
    branches:
      - ${{ github.event.release.target_commitish }}
  
jobs:
  php-cs-fixer:
    uses: nickbeen/.github/.github/workflows/php-cs-fixer.yml@main
