name: Run tests

on:
    pull_request:

jobs:
    run-tests:

        strategy:
            fail-fast: false
            matrix:
                php: [8.3, 8.2, 8.1, 8.0]
                os: [ubuntu-latest, windows-latest]

        name: PHP ${{ matrix.php }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Setup problem matcher
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: composer update --prefer-dist

            - name: Run tests
              run: vendor/bin/phpunit
